# create new issue using the gh pkg
name: Open a new issue in a repo
on: push

jobs:
  test-issue-open:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: install the gh pkg
        run: |
          install.packages("gh")
        shell: Rscript {0}
      - name: Create an issue
        run: |
          gh::gh("POST /repos/{owner}/{repo}/issues",
           owner = "k-doering-noaa", 
           repo = "learn_tmb", 
           title = "test issue again",
           body = paste0("Test out making an issue again"))
        shell: Rscript {0}
        
