name: Create an issue
on: push
jobs:
  create_issue:

    runs-on: ubuntu-latest
    steps:
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo: k-doering-NOAA/learn_tmb
          title: Test making an issue
          body: |
            ## This week's TODO (please ignore this)
            
            - [ ] Have a meeting with UX team
            - [ ] Check the dashboard
